---
title: A conversation about EDIA in the RSE community
subtitle: Reflections on successes and challenges
author: 
  - name: Ella Kaye (@EllaKaye) and Malvika Sharan (@malvikasharan)
  - name: diveRSE
date: 2024-07-31
date-format: long
format:
  warwickpres-revealjs: 
    slide-number: false
---

## Overview

- Introductions / positionality
- Malvika and Ella in conversation
- Open Q&A and discussion with participants

## Malvika

- Researcher, **Community Facilitator**, The Alan Turing Institute
- Lead of **Research Community Management team** - *connecting projects, teams, software, communities*
- **The Turing Way** - *a global community-led project on data science practices, advocacy and culture change*
- **OLS** (formerly Open Life Science) - *a global community of learners and practitioners of open science*
- Embedded in open source/science communities, building on RSE movement!

## Positionality (Malvika)

**under-represented in RSE / minority positions**

- Asian, woman
- Not really RSE - but RSE adjacent!
- Advocate of open science and community management in research - often met with skepticism and dismissal

**over-represented / privilege**

- cisgender, financial stability, access to privileged groups

## Ella

- RSE, Warwick, "Sustainability and EDI in the R Project" (with Heather Turner)
- rainbowR; SSI inclusive

. . .

### Positionality

**under-represented in RSE / minority positions**

- woman, gay

**over-represented / privilege**

- White, cisgender, global north, financial stability, elite education

## Discussion questions/themes

::: {.incremental}

- What have been our experiences in RSE or research as members of under-represented or over-represented communities?
- [What challenges have we faced when pushing for more EDIA in the RSE community?]{.gray}
- The importance and difficulties of community-building and why it matters from an EDIA perspective
- [Intersectionality between developing an RSE identity and identities as members of groups under-represented in the broader RSE community]{.gray}
- What are the links between EDIA and justice?
- [Positive examples of groups and initiatives where EDIA was improved]{.gray}
:::

## Resources

- RainbowR: [rainbowr.org](https://rainbowr.org/)
- *The Turing Way*: [book.the-turing-way.org](https://book.the-turing-way.org/)
- OLS: [we-are-ols.org](https://we-are-ols.org/)
- Resource list: [bit.ly/2024-07-31-diverse-session](https://annuel2.framapad.org/p/2024-07-31-diverse-session)

```{=html}
<!-- needs to be last chunk of presentation otherwise creates an extra slide -->
<!-- requires Quarto v1.3 -->
<!-- tint80 for border, tint20 for title -->
<!-- this should hopefully no longer be necessary in a future version of Quarto -->
<!-- https://github.com/quarto-dev/quarto-cli/issues/5038 -->
<style type="text/css">
div.callout-note {
  border-left-color: #00A9CE !important;
}

div.callout-note.callout-style-default .callout-title {
  background-color: #B3E5F0 !important;
}

div.callout-warning {
  border-left-color: #CB333B !important;
}

div.callout-warning.callout-style-default .callout-title {
  background-color: #EEC3C3 !important;
}

div.callout-tip {
  border-left-color: #6DCDB8 !important;
}

div.callout-tip.callout-style-default .callout-title {
  background-color: #D3F0EB !important;
}

div.callout-important {
  border-left-color: #F1BE48 !important;
}

div.callout-important.callout-style-default .callout-title {
  background-color: #FAECC8 !important;
}

div.callout-caution {
  border-left-color: #E87722 !important;
}

div.callout-caution.callout-style-default .callout-title {
  background-color: #F8D5BC !important;
}
</style>
```
